/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jong' at '4/27/15 10:08 PM' with Gradle 2.3
 *
 * @author jong, @date 4/27/15 10:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
